WEBGISQN/urls.py
from django.contrib import admin
from django.urls import path
from qlcayxanh.views import *
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/',loginPageView.as_view(),name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
    url(r'^index/', include(('qlcayxanh.urls','qlcayxanh'), namespace='qlcayxanh')),
    path('index/', index.as_view(), name='index'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

qlcayxanh/urls.py
from django.urls import path
from qlcayxanh.views import *
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url

urlpatterns = [
    # Tài khoản user
    url(r'^list_users/$', listuser, name='users'),
    url(r'^adduser/$', register, name='adduser'),
    path('update_user/<str:pk>/', updateUser, name="update_user"),
    path('delete_Userpopup/<str:pk>/', deleteUserpopup, name="delete_Userpopup"),
    url(r'^change_password/$', change_password, name='change_password'),
    # ranh giới
    url(r'^list_boundarys/$', list_ranhgioi, name='boundarys'),
    url(r'^add_boundarys/$', create_boundary, name='add_boundary'),
    path('update_boundarys/<str:pk>/', update_boundary, name="update_boundary"),
    path('delete_boundarypopup/<str:pk>/', delete_boundarypopup, name="delete_boundarypopup"),
    path('inf_boundarys/<str:pk>/', inf_boun, name="inf_boun"),
    # ĐƯờng giao thông
    url(r'^list_street/$', liststreets, name='liststreets'),
    url(r'^add_street/$', addstreets, name='addstreets'),
    path('update_streets/<str:pk>/', update_streets, name="update_streets"),
    path('delete_streets/<str:pk>/', delete_streets, name="delete_streets"),
    path('inf_streets/<str:pk>/', inf_street, name="inf_street"),
    # popio
    # Cây xanh
    url(r'^list_trees/$', listtrees, name='listtrees'),
    url(r'^add_tree/$', addcayxanh, name='addcayxanh'),
    path('update_trees/<str:pk>/', update_trees, name="update_trees"),
    path('delete_trees/<str:pk>/', delete_trees, name="delete_trees"),
    path('inf_trees/<str:pk>/', inf_tree, name="inf_tree"),
    # Nhân viên
    url(r'^list_staffs/$', lists_staff, name='lists_staff'),
    url(r'^add_staff/$', addstaffs, name='addstaffs'),
    path('update_staffs/<str:pk>/', update_staffs, name="update_staffs"),
    path('delete_staffs/<str:pk>/', delete_staffs, name="delete_staffs"),
    # Thống kê
    url(r'^list_statis/$', statis, name='statis'),
    path('inf_tree/<str:pk>/', inf_trees, name="inf_trees"),

    # chăm sóc cây
    url(r'^list_tcotrees/$', lists_tcotrees, name='lists_tcotrees'),
    url(r'^add_tcotrees/$', addtcotrees, name='addtcotrees'),
    path('update_tcotrees/<str:pk>/', update_tcotrees, name="update_tcotrees"),
    path('delete_tcotrees/<str:pk>/', delete_tcotrees, name="delete_tcotrees"),
    path('inftco_trees/<str:pk>/', inftco_trees, name="inftco_trees"),
    path('inftco_staff/<str:pk>/', inftco_staff, name="inftco_staff"),
#Loại cây
    url(r'^list_typetrees/$', typetrees, name='typetrees'),
    url(r'^add_typetree/$', addtypetrees, name='addtypetrees'),
    path('update_typetrees/<str:pk>/', update_typetrees, name="update_typetrees"),
    path('delete_typetreespopup/<str:pk>/', delete_typetreespopup, name="delete_typetreespopup"),
#tình trạng cây
    url(r'^list_contrees/$', contrees, name='contrees'),
    url(r'^add_contree/$', addcon, name='addcon'),
    path('update_contrees/<str:pk>/', update_con, name="update_con"),
    path('delete_contreespopup/<str:pk>/', delete_con, name="delete_con"),
    # footer
    # Tương tác bản đồ
    path('map/', show_data, name="map"),
    path('child_tree/',child_tree, name = 'childtree'),
    path('child_street/',child_street, name = 'childstreet'),
    path('child_boun/',child_boun, name = 'childboun'),
    # ######
    path('class/<str:id>/', child_da, name="class"),
# export pdf danh sách cây

    path('export_pdf/', export_pdf, name="export-pdf"),







]

qlcayxanh/views.py
from django.contrib import auth
from django.contrib import messages
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from django import forms
from django.views.generic import TemplateView, FormView
from django.contrib.auth.models import User
from rest_framework import generics, permissions
from django.contrib.auth.views import LoginView, LogoutView

from qlcayxanh.filters import treeFilter
from qlcayxanh.forms import *
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate
from django.views import View
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UsernameField
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import logout
import xlwt
from datetime import datetime
from django.db.models import Q, Count
# Create your views here.
from qlcayxanh.models import ranh_gioi, cayxanh, duonggiaothong,loaicay
from django.db.models import Sum,Value as V
from django.db.models.functions import Concat
from django.shortcuts import render, get_object_or_404
from django.core import serializers
from django.contrib.gis.serializers.geojson import Serializer
from datetime import date
from django.template.loader import render_to_string
from weasyprint import HTML
import tempfile
#----------------

#---------------
# Đăng nhập
class loginPageView(LoginView):
    def get(self, request):
        if not request.user.is_authenticated:
            return render(request, 'login/login.html')
        else:
            user = User.objects.filter(id=request.user.pk)
            if user[0].is_superuser:
                return redirect('/index/')
            else:
                return redirect('/index/')
    def post(self, request):
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = User.objects.filter(username=username)
            if user:
                if user[0].is_active:
                    user_auth = authenticate(username=username, password=password)
                    if user_auth:
                        login(request, user_auth)
                        if user[0].is_superuser:
                            return redirect('/index/')
                        else:
                            return redirect('/index/')
                    else:
                        return render(request, 'login/login.html', {
                            'alert': 'Bạn hãy nhập đúng Tên tài khoản và mật khẩu. (Có phân biệt chữ hoa, thường)'})
                else:
                    return render(request, 'login/login.html',
                                  {'alert': 'Tài khoản của bạn chưa được kích hoạt. Vui lòng liên hệ với Quản trị.'})
            else:
                return render(request, 'login/login.html',
                              {'alert': 'Tài khoản của bạn chưa có. Liên hệ với Quản trị để tạo tài khoản.'})


# --------------------------
# logout
class Logout(View):
    @login_required(login_url='login/')
    def logout(self, request):
        auth.logout(request)
        return redirect('/login/')
#----------------------------------------



class index(LoginRequiredMixin, TemplateView):
    template_name = 'index.html'




# quản lý người sử dụng
def listuser(request):
    listusers = User.objects.all()
    expenses = User.objects.all()
    query = request.GET.get('q')
    if query:
        expenses = User.objects.annotate(
                        full_name=Concat('last_name', V(' '), 'first_name')
                    ).filter(
            Q(username__icontains=query)| Q(first_name__icontains=query)| Q(last_name__icontains=query)| Q(full_name__icontains=query)
        ).distinct()
    paginator = Paginator(expenses, 10)  # Phân trang với pagination
    page_number = request.GET.get('page')
    page_obj = Paginator.get_page(paginator, page_number)
    return render(request, 'home/qlusers/users.html', {"listusers": listusers,'page_obj':page_obj})

#-----------------------------

#---------------------------------
    
# Tạo tài khoản
#---------------------------------
def register(request):
    firstname=''
    lastname=''
    emailvalue=''
    uservalue=''
    passwordvalue1=''
    passwordvalue2=''
    is_staffvalue = ''
    is_activevalue = ''
    is_superuservalue = ''
    listusers = User.objects.all()
    form= RegistrationForm(request.POST or None)
    if form.is_valid():
        fs= form.save(commit=False)
        firstname= form.cleaned_data.get("first_name")
        lastname= form.cleaned_data.get("last_name")
        emailvalue= form.cleaned_data.get("email")
        uservalue= form.cleaned_data.get("username")
        passwordvalue1= form.cleaned_data.get("password1")
        passwordvalue2= form.cleaned_data.get("password2")
        is_staffvalue = form.cleaned_data.get("is_staff")
        is_activevalue = form.cleaned_data.get("is_active")
        is_superuservalue = form.cleaned_data.get("is_superuser")
        if passwordvalue1 == passwordvalue2:
            user= User.objects.create_user(username=uservalue, password= passwordvalue1, email=emailvalue,first_name=firstname,last_name=lastname,is_staff=is_staffvalue,  is_active=is_activevalue,is_superuser=is_superuservalue  )
            user.save()
            return redirect('/index/list_users')
            context= {'form': form,'listusers': listusers}
            return render(request, 'home/qlusers/users.html', context)
        else:
            context= {'form': form, 'error':'The passwords that you provided don\'t match'}
            return render(request, 'home/qlusers/add.html', context)
    else:
        context= {'form': form,'listusers': listusers}
        return render(request, 'home/qlusers/add.html', context)

# Chỉnh sửa tài khoản
def updateUser(request, pk):
    user = User.objects.get(id=pk)
    form = UserForm(instance=user)
    if request.method == 'POST':
        form = UserForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            messages.success(request, 'Cập nhật thành công!')
            return redirect(reverse('qlcayxanh:users'))

    context = {'form': form, 'user': user}
    return render(request, 'home/qlusers/edit.html', context)

# Xóa tài khoản
def deleteUserpopup(request, pk):
    user = User.objects.get(id=pk)
    listusers = User.objects.all()
    if request.method == "POST":
        user.delete()
        messages.success(request, 'Xóa thành công!')
        return redirect(reverse('qlcayxanh:users'))
        context = {'item': user,'listusers':listusers}
        return render(request, 'home/qlusers/users.html', context)
    context = {'item': user}
    return render(request, 'home/qlusers/users.html', context)

# Thay đổi mật khẩu người đăng nhập
def change_password(request):
    if request.method == 'POST':
        form = Password_ChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Mật khẩu của bạn đã được cập nhật!')
            return redirect(reverse('qlcayxanh:change_password'))
        else:
            messages.error(request, 'Vui lòng sửa lỗi bên dưới!')
    else:
        form = Password_ChangeForm(request.user)
    return render(request, 'home/qlusers/change_pass.html', {
        'form': form
    })

# quản lý dữ liệu

# quản lý ranh giới
def list_ranhgioi(request):
    listboundarys = ranh_gioi.objects.all()
    expenses = ranh_gioi.objects.all()
    query = request.GET.get('q')
    if query:
        expenses = ranh_gioi.objects.filter(
            Q(ma_ranh_gioi__icontains=query) | Q(ten_ranh_gioi__icontains=query)
        ).distinct()
    paginator = Paginator(expenses, 5)  # Phân trang với pagination
    page_number = request.GET.get('page')
    page_obj = Paginator.get_page(paginator, page_number)
    return render(request, 'home/qldatas/qlboundarys/boundarys.html', {"listboundarys": listboundarys,'page_obj':page_obj})

# Tạo ranh giới
def create_boundary(request):
    form = ranhgioiForm()
    if request.method == 'POST':
        form = ranhgioiForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('qlcayxanh:boundarys'))

    context = {'form': form}
    return render(request, 'home/qldatas/qlboundarys/add.html', context)

# Chỉnh sửa ranh giới
def update_boundary(request, pk):
    boun = ranh_gioi.objects.get(ma_ranh_gioi=pk)
    form = ranhgioiForm(instance=boun)
    if request.method == 'POST':
        form = ranhgioiForm(request.POST, instance=boun)      
        if form.is_valid():
            form.save()
            messages.success(request, 'Cập nhật thành công!')
            return redirect(reverse('qlcayxanh:boundarys'))

    context = {'form': form,'boun':boun}
    return render(request, 'home/qldatas/qlboundarys/edit.html', context)
# Xóa ranh giới
def delete_boundarypopup(request, pk):
    boundary = ranh_gioi.objects.get(ma_ranh_gioi=pk)
    listboundarys = ranh_gioi.objects.all()
    if request.method == "POST":
        boundary.delete()
        messages.success(request, 'Xóa thành công!')
        return redirect(reverse('qlcayxanh:boundarys'))
    context = {'item': boundary}
    return render(request, 'home/qldatas/qlboundarys/boundarys.html', context)
def inf_boun(request, pk):
    boun = ranh_gioi.objects.get(ma_ranh_gioi=pk)
    form = ranhgioiForm(instance=boun)
    if request.method == 'POST':

qlcayxanh/templates/include/base.html
<style>
</style>
{% load static %}
<nav class="navbar navbar-default top-navbar" role="navigation">
    <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
                    <span class="sr-only"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

    </div>
    <ul class="nav navbar-top-links navbar-right">
       
        <!-- /.dropdown -->
     
        <!-- /.dropdown -->
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#" aria-expanded="false">
               <i class="fa fa-comments-o" aria-hidden="true"></i>
            </a>
            <ul class="dropdown-menu dropdown-user">
                <li><a href="" >
                    Không có thông báo.
                    </a>
                </li>
            </ul>
        </li>
        <!-- /.dropdown -->
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#" aria-expanded="false">
            <img src="{% static 'home/img/7.jpg' %}" alt="user" class="profile-pic me-2"> {{user}} <i class="fa fa-caret-down"></i>
            </a>
            <ul class="dropdown-menu dropdown-user">
                <li><a href="" data-toggle="modal" data-target="#userprofile"><i class="fa fa-info-circle" aria-hidden="true"></i>
                    Thông tin người dùng
                    </a>
                </li>
                <li><a href="{% url 'qlcayxanh:change_password' %}"  ><i class="fa fa-cog fa-spin"></i>
                    Đổi mật khẩu
                    </a>
                </li>
                 {% if user.is_superuser  %}
                <li><a href="{% url 'qlcayxanh:users' %}" ><i class="fa fa-users" aria-hidden="true"></i>
                    Tài khoản hệ thống
                    </a>
                </li>
                {% endif %}
                <li class="divider"></li>
                <li><a href="{% url 'logout' %}"><i class="fa fa-power-off text-danger"></i> Đăng xuất</a>
                </li>
            </ul>
            <!-- /.dropdown-user -->
        </li>
        <!-- Đăng xuất -->
        <li class="dropdown">
            <li><a href="{% url 'logout' %}"><i class="fa fa-sign-out text-danger"></i></a>
            <!-- /.dropdown-alerts -->
        </li>
        <!-- /.dropdown -->
    </ul>
</nav>
<!--/. NAV TOP  -->
<nav class="navbar-default navbar-side" role="navigation">
    <div class="sidebar-collapse force-scroll" id="#style-1">
        <ul class="nav" id="main-menu">
            <li>
                <img class='img' src="{% static 'home/img/logo2.png' %}"/>
            </li>
            <li>
                <a href="{% url 'index' %}"><i class="fa fa-home" aria-hidden="true"></i>Trang chủ</a>
            </li>
            <li>
                <a href="{% url 'qlcayxanh:map' %}"><i class="fa fa-globe" aria-hidden="true"></i>Bản đồ</a>
            </li>
             {% if user.is_superuser %}
            <li>
                <a href="{% url 'qlcayxanh:lists_staff' %}"><i class="fa fa-users" aria-hidden="true"></i>Quản lý nhân viên</a>
            </li>
             {% endif %}
            <!-- Quản lý dữ liệu -->
            <li>
                <a  href="#"><i class="fa fa-chain-broken" aria-hidden="true"></i>Quản lý dữ liệu<span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                     <li>
                        <a href="{% url 'qlcayxanh:boundarys' %}">Ranh giới</a>
                    </li>
                     <li>
                        <a href="{% url 'qlcayxanh:liststreets' %}">Đường giao thông</a>
                    </li>
                    <li>
                        <a href="{% url 'qlcayxanh:listtrees' %}">Cây</a>
                    </li>


                </ul>
            </li>
            <!-- Quản lý chăm soc cây	 -->
            <li>
                <a href="{% url 'qlcayxanh:lists_tcotrees' %}"><i class="fa fa-pagelines" aria-hidden="true"></i>Chăm sóc cây</a>
            </li>
<!--            Thống kê/ báo cáo-->
            <li>
                <a href=" {% url 'qlcayxanh:statis' %}"><i class="fa fa-stack-exchange" aria-hidden="true"></i>Thống kê</a>
            </li>
            <!-- Tương tác bản đồ -->

            <!-- Tìm kiếm  -->

            <!-- Thư viện -->

        </ul>
    </div>
</nav>
<!-- /. NAV SIDE  -->
<!-- Modal  thôgn tin người dùng-->
<div class="modal fade" id="userprofile" tabindex="-1" role="dialog" aria-labelledby="userprofileLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" style="text-align:center;color:#8BC34A; " id="userprofileLabel">Thông tin người dùng
                </h4>
                <button style=" margin-top: -25px;" type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <table class="table table-user-information">
                    <tbody>
                        <tr>
                            <td >Tên đăng nhập:</td>
                            <td >{{ user }}</td>
                        </tr>
                        <tr>
                            <td style="border-top: 1px solid #ddd;">Họ và tên:</td>
                            <td style="border-top: 1px solid #ddd;">{{ user.last_name }} {{ user.first_name }}</td>
                        </tr>
                        <tr>
                            <td style="border-top: 1px solid #ddd;">Email:</td>
                            <td style="border-top: 1px solid #ddd;">{{ user.email }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="modal-footer">
            </div>
        </div>
    </div>
</div>

qlcayxanh/templates/include/filescript.html
{% load static %}

<!--    menu-->
    <script type="text/javascript" src="{% static 'home/js/jquery-1.10.2.js' %}">  </script>

    <script type="text/javascript" src="{% static 'home/js/jquery.metisMenu.js' %}">  </script>
    <!-- Bootstrap Js -->
    <script type="text/javascript" src="{% static 'home/js/bootstrap.min.js' %}">  </script>
    <!-- Metis Menu Js -->
    <!--full screen  Js -->
    <script type="text/javascript" src="{% static 'home/js/morris/raphael-2.1.0.min.js' %}">  </script>
    <script type="text/javascript" src="{% static 'home/js/morris/morris.js' %}">  </script>
    <script type="text/javascript" src="{% static 'home/js/Lightweight-Chart/jquery.chart.js' %}">  </script>
    <!-- Custom Js -->
    <script type="text/javascript" src="{% static 'home/js/custom-scripts.js' %}">  </script>

qlcayxanh/templates/include/includecss.html
{% load static %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Quản lý cây xanh đô thị
</title>
    <link rel="icon" type="image/png" href="{% static 'home/img/favicon.png' %}"/>
    <!-- Bootstrap Styles-->
    <link rel="stylesheet"  href="{% static 'home/css/bootstrap.css' %}"  />
     <link rel="stylesheet"  href="{% static 'home/css/menu.css' %}"  />
    <!-- FontAwesome Styles-->
    <link rel="stylesheet"  href="{% static 'home/css/font-awesome.css' %}"  />
    <!-- Morris Chart Styles-->
<style>
      a.leaflet-bar-part{
                display:none;
            }
</style>