WEBGISQN/urls.py
from django.contrib import admin
from django.urls import path
from qlcayxanh.views import *
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/',loginPageView.as_view(),name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
    url(r'^index/', include(('qlcayxanh.urls','qlcayxanh'), namespace='qlcayxanh')),
    path('index/', index.as_view(), name='index'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

qlcayxanh/urls.py
from django.urls import path
from qlcayxanh.views import *
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url

urlpatterns = [
    # Tài khoản user
    url(r'^list_users/$', listuser, name='users'),
    url(r'^adduser/$', register, name='adduser'),
    path('update_user/<str:pk>/', updateUser, name="update_user"),
    path('delete_Userpopup/<str:pk>/', deleteUserpopup, name="delete_Userpopup"),
    url(r'^change_password/$', change_password, name='change_password'),
    # ranh giới
    url(r'^list_boundarys/$', list_ranhgioi, name='boundarys'),
    url(r'^add_boundarys/$', create_boundary, name='add_boundary'),
    path('update_boundarys/<str:pk>/', update_boundary, name="update_boundary"),
    path('delete_boundarypopup/<str:pk>/', delete_boundarypopup, name="delete_boundarypopup"),
    path('inf_boundarys/<str:pk>/', inf_boun, name="inf_boun"),
    # ĐƯờng giao thông
    url(r'^list_street/$', liststreets, name='liststreets'),
    url(r'^add_street/$', addstreets, name='addstreets'),
    path('update_streets/<str:pk>/', update_streets, name="update_streets"),
    path('delete_streets/<str:pk>/', delete_streets, name="delete_streets"),
    path('inf_streets/<str:pk>/', inf_street, name="inf_street"),
    # popio
    # Cây xanh
    url(r'^list_trees/$', listtrees, name='listtrees'),
    url(r'^add_tree/$', addcayxanh, name='addcayxanh'),
    path('update_trees/<str:pk>/', update_trees, name="update_trees"),
    path('delete_trees/<str:pk>/', delete_trees, name="delete_trees"),
    path('inf_trees/<str:pk>/', inf_tree, name="inf_tree"),
    # Nhân viên
    url(r'^list_staffs/$', lists_staff, name='lists_staff'),
    url(r'^add_staff/$', addstaffs, name='addstaffs'),
    path('update_staffs/<str:pk>/', update_staffs, name="update_staffs"),
    path('delete_staffs/<str:pk>/', delete_staffs, name="delete_staffs"),
    # Thống kê
    url(r'^list_statis/$', statis, name='statis'),
    path('inf_tree/<str:pk>/', inf_trees, name="inf_trees"),

    # chăm sóc cây
    url(r'^list_tcotrees/$', lists_tcotrees, name='lists_tcotrees'),
    url(r'^add_tcotrees/$', addtcotrees, name='addtcotrees'),
    path('update_tcotrees/<str:pk>/', update_tcotrees, name="update_tcotrees"),
    path('delete_tcotrees/<str:pk>/', delete_tcotrees, name="delete_tcotrees"),
    path('inftco_trees/<str:pk>/', inftco_trees, name="inftco_trees"),
    path('inftco_staff/<str:pk>/', inftco_staff, name="inftco_staff"),
#Loại cây
    url(r'^list_typetrees/$', typetrees, name='typetrees'),
    url(r'^add_typetree/$', addtypetrees, name='addtypetrees'),
    path('update_typetrees/<str:pk>/', update_typetrees, name="update_typetrees"),
    path('delete_typetreespopup/<str:pk>/', delete_typetreespopup, name="delete_typetreespopup"),
#tình trạng cây
    url(r'^list_contrees/$', contrees, name='contrees'),
    url(r'^add_contree/$', addcon, name='addcon'),
    path('update_contrees/<str:pk>/', update_con, name="update_con"),
    path('delete_contreespopup/<str:pk>/', delete_con, name="delete_con"),
    # footer
    # Tương tác bản đồ
    path('map/', show_data, name="map"),
    path('child_tree/',child_tree, name = 'childtree'),
    path('child_street/',child_street, name = 'childstreet'),
    path('child_boun/',child_boun, name = 'childboun'),
    # ######
    path('class/<str:id>/', child_da, name="class"),
# export pdf danh sách cây

    path('export_pdf/', export_pdf, name="export-pdf"),







]

qlcayxanh/models.py
from django.db import models
from django.contrib.gis.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.conf import settings
import django.db.models.deletion
from django.db.models.signals import post_save
from django.dispatch import receiver

from django.db import models
from django.contrib.gis.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.conf import settings
import django.db.models.deletion
from django.db.models.signals import post_save
from django.dispatch import receiver

from django.db import models
from django.contrib.gis.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.conf import settings
import django.db.models.deletion
from django.db.models.signals import post_save
from django.dispatch import receiver


class nhanvien(models.Model):
    GENRE_CHOICES = (
        ('Nam', 'Nam'),
        ('Nữ', 'Nữ'),
    )
    ma_nhan_vien = models.CharField('Mã nhân viên', max_length=100, primary_key=True)
    hoten = models.CharField('Họ và tên', max_length=100)
    gioitinh = models.CharField(max_length=3, choices=GENRE_CHOICES)
    dienthoai = models.IntegerField(default=0)
    diachi = models.CharField('Địa chỉ', max_length=255, null=True, blank=True)

    def __str__(self):
        return self.hoten


class ranh_gioi(models.Model):
    GENRE_CHOICES = (
        ('Phường', 'Phường'),
        ('Xã', 'Xã'),
    )
    ma_ranh_gioi = models.CharField('Mã ranh giới',max_length=100, primary_key=True)
    ten_ranh_gioi = models.CharField('Tên ranh giới', max_length=100)
    type_ranh_gioi= models.CharField('Loại ranh giới',max_length=6, choices=GENRE_CHOICES)
    geom = models.MultiPolygonField(srid=4326)
    ghichu = models.CharField(max_length=150, null=True, blank=True)
    def __str__(self):
        return self.ten_ranh_gioi
    def natural_key(self):
        return (self.ten_ranh_gioi)


class duonggiaothong(models.Model):
    ma_duong = models.CharField('Mã đường', max_length=100, primary_key=True)
    ten_duong = models.CharField('Tên đường', max_length=100)
    geom = models.MultiLineStringField(srid=4326)
    ghichu = models.CharField(max_length=150, null=True, blank=True)
    ranh_gioi_id = models.ForeignKey(ranh_gioi, verbose_name="Tên ranh giới", on_delete=models.CASCADE)

    def __str__(self):
        return self.ten_duong

    def natural_key(self):
        return (self.ten_duong)


class loaicay(models.Model):
    ma_loai_cay = models.CharField('mã loại cây', max_length=50, primary_key=True)
    ten_loai_cay = models.CharField('tên loại cây', max_length=100)

    def __str__(self):
        return self.ten_loai_cay

    def natural_key(self):
        return (self.ten_loai_cay)

class tinhtrangcay(models.Model):
    ten_tinh_trang= models.CharField('tên tình trạng cây', max_length=100)

    def __str__(self):
        return self.ten_tinh_trang

    def natural_key(self):
        return (self.ten_tinh_trang)


class cayxanh(models.Model):
    ma_cay = models.CharField(max_length=100, primary_key=True)
    ten_cay = models.CharField(max_length=100)
    chieucao = models.IntegerField()
    vitri = models.CharField(max_length=100)
    ngaytrong = models.DateField('Ngày trồng')
    tinhtrang_id = models.ForeignKey(tinhtrangcay, verbose_name="Tình trạng", on_delete=models.CASCADE)
    dacdiem = models.CharField('Đặc điểm ', max_length=200, null=True, blank=True)
    geom = models.PointField(srid=4326)
    duong_id = models.ForeignKey(duonggiaothong, verbose_name="Tên đường giao thông", on_delete=models.CASCADE)
    loaicay_id = models.ForeignKey(loaicay, verbose_name="Loại cây", on_delete=models.CASCADE)


    def __str__(self):
        return self.ma_cay

class chamsoccay(models.Model):
    cong_viec = models.CharField('Công việc', max_length=100)
    ngay_cham_soc = models.DateField('Ngày chăm sóc')
    nhanvien_id = models.ForeignKey(nhanvien, verbose_name="Nhân viên ", on_delete=models.CASCADE)
    cayxanh_id = models.ForeignKey(cayxanh, verbose_name="Cây xanh", on_delete=models.CASCADE)

    def __unicode__(self):
        return self.cayxanh_id

qlcayxanh/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm,SetPasswordForm
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from django.forms import ModelForm
from qlcayxanh import models
from qlcayxanh.models import *
from django.contrib.gis.db.models import MultiPolygonField
from django.contrib.gis import forms
from leaflet.forms.widgets import LeafletWidget
LEAFLET_WIDGET_ATTRS = {
    'map_height': '600px',
    'map_width': '50%',
    'display_raw': 'true',
    'map_srid': 4326,
}

class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True, label='Email')
    first_name = forms.CharField(max_length=30, required=False, help_text='Không bắt buộc.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Không bắt buộc')
    username = forms.CharField(required=True, help_text = _('Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.'))
    is_staff= forms.BooleanField(required=False)
    is_active = forms.BooleanField(required=False)
    is_superuser = forms.BooleanField(required=False)
    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'is_staff',
            'is_active',
            'is_superuser'
        )


class UserForm(UserChangeForm):
    class Meta:
        model = User
        fields = (
            'email',
            'first_name',
            'last_name',
            'is_staff',
            'is_active',
            'is_superuser'
        )

class Password_ChangeForm(SetPasswordForm):
    """
    A form that lets a user change their password by entering their old
    password.
    """
    error_messages = {
        **SetPasswordForm.error_messages,
        'password_incorrect': _("Mật khẩu cũ của bạn không đúng, vui lòng nhập lại."),
    }
    old_password = forms.CharField(
        label=_("Old password"),
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'current-password', 'autofocus': True}),
    )
    new_password1 = forms.CharField(  label=_("Nhập mật khẩu mới"),strip=False,widget=forms.PasswordInput(attrs={'autocomplete': 'current-password', 'autofocus': True}),help_text=(""))
    new_password2 = forms.CharField(label=_("Nhập lại mật khẩu mới"),strip=False,widget=forms.PasswordInput(attrs={'autocomplete': 'current-password', 'autofocus': True}),help_text=_(""))
    field_order = ['old_password', 'new_password1', 'new_password2']

    def clean_old_password(self):
        """
        Validate that the old_password field is correct.
        """
        old_password = self.cleaned_data["old_password"]
        if not self.user.check_password(old_password):
            raise ValidationError(
                self.error_messages['password_incorrect'],
                code='password_incorrect',
            )
        return old_password
# Nhân viên form
class nhanvienForm(ModelForm):
    class Meta:
        model = nhanvien
        fields = '__all__'
#---------------------------------------#
# ranh giới form
class ranhgioiForm(ModelForm):
    geom = forms.MultiPolygonField(
        widget=LeafletWidget(attrs=LEAFLET_WIDGET_ATTRS))
    class Meta:
        model = ranh_gioi
        fields = (
            'ma_ranh_gioi',
            'type_ranh_gioi',
            'ten_ranh_gioi',
            'geom',
            'ghichu'
        )
# cây xanh form
class cayxanhForm(ModelForm):
    geom = forms.PointField(
        widget=LeafletWidget(attrs=LEAFLET_WIDGET_ATTRS))
    class Meta:
        model = cayxanh
        fields = (
            'ma_cay',
            'ten_cay',
            'chieucao',
            'vitri',
            'ngaytrong',
            'tinhtrang_id',
            'dacdiem',
            'geom',
            'duong_id',
            'loaicay_id'
        )

# ----------------------------#
# Đường giao thông form
class streetsForm(ModelForm):
    geom = forms.MultiLineStringField(
        widget=LeafletWidget(attrs=LEAFLET_WIDGET_ATTRS))
    class Meta:
        model = duonggiaothong
        fields = (
            'ma_duong',
            'ten_duong',
            'geom',
            'ghichu',
            'ranh_gioi_id'
        )
# Chăm sóc cây
class chamsoccayForm(ModelForm):
    class Meta:
        model = chamsoccay
        fields = (
            'cong_viec',
            'ngay_cham_soc',
            'nhanvien_id',
            'cayxanh_id'
        )
class treeSearchForm(forms.ModelForm):
    class Meta:
        model = cayxanh
        fields = ['ma_cay','ten_cay','loaicay_id']

class loaicayForm(ModelForm):
    class Meta:
        model = loaicay
        fields = '__all__'

class tinhtrangcayForm(ModelForm):
    class Meta:
        model = tinhtrangcay
        fields = '__all__'

qlcayxanh/templates/home/qlusers/add.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
<head>
     {% include 'include/includecss.html' %}
    <link rel="stylesheet"  href="{% static 'home/qlusers/css/bootstrap.css' %}"  />
    <link rel="stylesheet"  href="{% static 'home/css/menu.css' %}"  />
    <!-- Custom Styles-->
    <link rel="stylesheet"  href="{% static 'home/qlusers/css/user.css' %}"  />
</head>
<body>
    <div id="wrapper">
        {% include 'include/base.html' %}
        <div id="page-wrapper">
        <div class="header">
            <div class="row user-infos cyruxx">
                <div class="col-xs-12 col-sm-12 col-md-10 col-lg-10 col-xs-offset-0 col-sm-offset-0 col-md-offset-1 col-lg-offset-1"></div>
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                                <h1 class="panel-title"> Thêm tài khoản</h1>
                            </div>
                        <div class="panel-body">
                            {% if form.errors %}
                            {% for field in form %}
                            {% for error in field.errors %}
                            <div class="alert alert-danger">
                                <strong>{{ error|escape }}</strong>
                            </div>
                            {% endfor %}
                            {% endfor %}
                            {% endif %}


                            <form method="post">
                                {% csrf_token %}
                                <div class="post_name"><label class="col-sm-3 col-form-label" for="id_username">Tên đăng nhập(<span style="color:red;">*</span>):</label>
                                    <input type="text" name="username" autofocus required id="id_username"style="background-color:#5897fb !important;color:#f8f9fc;">
                                    <div id="uname_error_pass" class="text-danger" ></div>
                                </div>
                                <div class="post_name">
                            <label class="col-sm-3 col-form-label" for="id_first_name">Họ và tên(<span style="color:red;">*</span>):</label>
                                <div class="col-sm-7 input-group" >
                                    <input type="text" name="last_name" maxlength="30" id="id_last_name" required data-validate="Họ và tên lót bắt buộc nhập">
                                    <input type="text" name="first_name" maxlength="30" id="id_first_name"required data-validate="Tên bắt buộc nhập">
                                        <br/>
                            <div id="uname_error_msg" class="text-danger"></div>
                                </div>
                                </div>
                                <div class="post_name">  <label class="col-sm-3 col-form-label" for="id_email">Email(<span style="color:red;">*</span>):</label>
                                    <input type="email" name="email" id="id_email"required data-validate="Email bắt buộc nhập" aria-describedby="emailHelp">
                                <div id="uname_error_email" class="error_email text-danger" ></div>
                                </div>

                                <div class="check_a" >
                                <label class="col-sm-3 col-form-label" for="id_is_staff">Nhân viên:</label> <input type="checkbox" name="is_staff" id="id_is_staff">
                            
                            </div>
                                <div class="check_a">
                                <label class="col-sm-3 col-form-label" for="id_is_active">Kích hoạt:</label> <input type="checkbox" name="is_active" id="id_is_active">
                                </div>
                                <div class="check_a">
                                <label class="col-sm-3 col-form-label" for="id_is_superuser">Trạng thái superuser:</label> <input type="checkbox" name="is_superuser" id="id_is_superuser">
                                </div>
                                <div class="post_name"><label class="col-sm-3 col-form-label" for="id_password1">Mật khẩu(<span style="color:red;">*</span>):</label>
                                    <input type="password"required  name="password1"autocomplete="new-password" style="background-color:#f6c23e !important;" id="id_password1">
                                </div>
                                <div class="post_name"><label class="col-sm-3 col-form-label" for="id_password2">Xác nhận mật khẩu(<span style="color:red;">*</span>):</label>
                                    <input type="password"required  name="password2" autocomplete="new-password" style="background-color:#f6c23e !important;"id="id_password2">
                                </div>
                                    <div class="post_center">

                                <span class="badge badge-danger" style="font-size:12px;">Trường có dấu (*) bắt buột phải nhập.</span>
                                    </div>
                                    <div class="post_center">
                                         <button class="submit-btn" type="submit" >Thêm</button>

                                    </div>

                            </form>
                        </div>
                    </div>
                        </div>
                        <a href="{% url 'qlcayxanh:users' %}">Quay về danh sách</a>
                    </div>
                </div>
            </div>
        </div>
        </div>
    </div>
    <!-- #main -->
       {% include 'include/filescript.html' %}
    <script src="{% static 'home/qlusers/js/validuser.js' %}"></script>
</body>
</html>

qlcayxanh/templates/home/qlusers/change_pass.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    <head>
   {% include 'include/includecss.html' %}
    <link rel="stylesheet"  href="{% static 'home/qlusers/css/bootstrap.css' %}"  />
    <link rel="stylesheet"  href="{% static 'home/css/menu.css' %}"  />
    <!-- Custom Styles-->
    <link rel="stylesheet"  href="{% static 'home/qlusers/css/adduser.css' %}"  />
        <!-- Custom Styles-->
    <link rel="stylesheet"  href="{% static 'home/qlusers/changepass/css/style.css' %}"  />

<style>
 .page-header {
            text-align: center;
            text-transform: uppercase;
            color:  #8BC34A;
            }
</style>
    </head>
    <body>
        <div id="wrapper">
        {% include 'include/base.html' %}
        <div id="page-wrapper" style="min-height: 570px;">
         
            <div id="page-inner" >
                <h2 class="page-header">ĐỔI MẬT KHẨU</h2>
                <div class="row">
                    <div class="center ">
                        <section class="get-in-touch">
                            {% for message in messages %}
                            <p id="messages" style="color:red;">{{message}}</p>
                            {% endfor %}
                            <form method="post"class="contact-form row" style="border: 1px solid #8BC34A;">
                                {% csrf_token %}
                                <div class="col-lg-12 ">
                                    {{ form.as_p }}
                                </div>
                                <div class="col-lg-12">
                                    <input class="submit-btn" type="submit" value="Cập nhật">
                                    <a class="cancel-btn " href="{% url 'index' %}" >Hủy</a>
                                </div>
                            </form>

                        </section>
                    </div>

                </div>
            </div>
        </div>
        </div>
          {% include 'include/filescript.html' %}

        <script src="{% static 'home/qlusers/js/validuser.js' %}"></script>
    </body>
</html>

qlcayxanh/templates/home/qlusers/edit.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    <head>
        {% include 'include/includecss.html' %}
    <link rel="stylesheet"  href="{% static 'home/qlusers/css/bootstrap.css' %}"  />
    <link rel="stylesheet"  href="{% static 'home/css/menu.css' %}"  />
    <!-- Custom Styles-->
     <link rel="stylesheet"  href="{% static 'home/qlusers/css/user.css' %}"  />
    </head>
    <body>
        <div id="wrapper">
            {% include 'include/base.html' %}
            <div id="page-wrapper">
                <div class="header">
                    <div class="row user-infos cyruxx">
                        <div class="col-xs-12 col-sm-12 col-md-10 col-lg-10 col-xs-offset-0 col-sm-offset-0 col-md-offset-1 col-lg-offset-1"></div>
                        <div class="panel panel-primary">
                            <div class="panel-heading">
                                <h1 class="panel-title">Chỉnh sửa tài khoản</h1>
                            </div>
                            <div class="panel-body">
    
                                <form method="post">
                                    {% csrf_token %}
                                    <div class="post_name"><label class="col-sm-3 col-form-label" for="id_email">Địa chỉ Email:</label> 
                                    <input type="email" name="email" value="{{ user.email }}" required maxlength="254" id="id_email"></div>
                                    <div class="post_name"><label  class="col-sm-3 col-form-label" for="id_first_name">Họ và tên:</label>
                                        <div class="col-sm-7 input-group" >
                                    <input type="text" name="last_name" value="{{ user.last_name  }} " required maxlength="30" id="id_last_name">
                                  <input type="text" name="first_name" value="{{ user.first_name }}"required maxlength="30" id="id_first_name">
                                </div>
                                </div>
                                    <div class="check_a" >
                                        <label class="col-sm-3 col-form-label" for="id_is_staff">Tình trạng: </label>{{ form.is_staff }}
                                       
                                        </div>
                                        <div class="check_a">
                                        <label class="col-sm-3 col-form-label" for="id_is_active">Kích hoạt:</label> {{ form.is_active }}
                                     
                                        </div>
                                        <div class="check_a">
                                        <label class="col-sm-3 col-form-label" for="id_is_superuser">Trạng thái superuser:</label> {{ form.is_superuser }}
                                       
                                    </div>
                                    <div class="post_center">
                                        <button class="submit-btn" type="submit">Cập nhật</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                    <a href="{% url 'qlcayxanh:users' %}">Quay về danh sách</a>
                </div>
            </div>
        </div>
        </div>
        </div>
        </div>
        <!-- #main -->
       {% include 'include/filescript.html' %}
    <script src="{% static 'home/qlusers/js/validuser.js' %}"></script>
    </body>
</html>