WEBGISQN/urls.py
from django.contrib import admin
from django.urls import path
from qlcayxanh.views import *
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/',loginPageView.as_view(),name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
    url(r'^index/', include(('qlcayxanh.urls','qlcayxanh'), namespace='qlcayxanh')),
    path('index/', index.as_view(), name='index'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

qlcayxanh/urls.py
from django.urls import path
from qlcayxanh.views import *
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url

urlpatterns = [
    # Tài khoản user
    url(r'^list_users/$', listuser, name='users'),
    url(r'^adduser/$', register, name='adduser'),
    path('update_user/<str:pk>/', updateUser, name="update_user"),
    path('delete_Userpopup/<str:pk>/', deleteUserpopup, name="delete_Userpopup"),
    url(r'^change_password/$', change_password, name='change_password'),
    # ranh giới
    url(r'^list_boundarys/$', list_ranhgioi, name='boundarys'),
    url(r'^add_boundarys/$', create_boundary, name='add_boundary'),
    path('update_boundarys/<str:pk>/', update_boundary, name="update_boundary"),
    path('delete_boundarypopup/<str:pk>/', delete_boundarypopup, name="delete_boundarypopup"),
    path('inf_boundarys/<str:pk>/', inf_boun, name="inf_boun"),
    # ĐƯờng giao thông
    url(r'^list_street/$', liststreets, name='liststreets'),
    url(r'^add_street/$', addstreets, name='addstreets'),
    path('update_streets/<str:pk>/', update_streets, name="update_streets"),
    path('delete_streets/<str:pk>/', delete_streets, name="delete_streets"),
    path('inf_streets/<str:pk>/', inf_street, name="inf_street"),
    # popio
    # Cây xanh
    url(r'^list_trees/$', listtrees, name='listtrees'),
    url(r'^add_tree/$', addcayxanh, name='addcayxanh'),
    path('update_trees/<str:pk>/', update_trees, name="update_trees"),
    path('delete_trees/<str:pk>/', delete_trees, name="delete_trees"),
    path('inf_trees/<str:pk>/', inf_tree, name="inf_tree"),
    # Nhân viên
    url(r'^list_staffs/$', lists_staff, name='lists_staff'),
    url(r'^add_staff/$', addstaffs, name='addstaffs'),
    path('update_staffs/<str:pk>/', update_staffs, name="update_staffs"),
    path('delete_staffs/<str:pk>/', delete_staffs, name="delete_staffs"),
    # Thống kê
    url(r'^list_statis/$', statis, name='statis'),
    path('inf_tree/<str:pk>/', inf_trees, name="inf_trees"),

    # chăm sóc cây
    url(r'^list_tcotrees/$', lists_tcotrees, name='lists_tcotrees'),
    url(r'^add_tcotrees/$', addtcotrees, name='addtcotrees'),
    path('update_tcotrees/<str:pk>/', update_tcotrees, name="update_tcotrees"),
    path('delete_tcotrees/<str:pk>/', delete_tcotrees, name="delete_tcotrees"),
    path('inftco_trees/<str:pk>/', inftco_trees, name="inftco_trees"),
    path('inftco_staff/<str:pk>/', inftco_staff, name="inftco_staff"),
#Loại cây
    url(r'^list_typetrees/$', typetrees, name='typetrees'),
    url(r'^add_typetree/$', addtypetrees, name='addtypetrees'),
    path('update_typetrees/<str:pk>/', update_typetrees, name="update_typetrees"),
    path('delete_typetreespopup/<str:pk>/', delete_typetreespopup, name="delete_typetreespopup"),
#tình trạng cây
    url(r'^list_contrees/$', contrees, name='contrees'),
    url(r'^add_contree/$', addcon, name='addcon'),
    path('update_contrees/<str:pk>/', update_con, name="update_con"),
    path('delete_contreespopup/<str:pk>/', delete_con, name="delete_con"),
    # footer
    # Tương tác bản đồ
    path('map/', show_data, name="map"),
    path('child_tree/',child_tree, name = 'childtree'),
    path('child_street/',child_street, name = 'childstreet'),
    path('child_boun/',child_boun, name = 'childboun'),
    # ######
    path('class/<str:id>/', child_da, name="class"),
# export pdf danh sách cây

    path('export_pdf/', export_pdf, name="export-pdf"),







]

qlcayxanh/models.py
from django.db import models
from django.contrib.gis.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.conf import settings
import django.db.models.deletion
from django.db.models.signals import post_save
from django.dispatch import receiver

from django.db import models
from django.contrib.gis.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.conf import settings
import django.db.models.deletion
from django.db.models.signals import post_save
from django.dispatch import receiver

from django.db import models
from django.contrib.gis.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.conf import settings
import django.db.models.deletion
from django.db.models.signals import post_save
from django.dispatch import receiver


class nhanvien(models.Model):
    GENRE_CHOICES = (
        ('Nam', 'Nam'),
        ('Nữ', 'Nữ'),
    )
    ma_nhan_vien = models.CharField('Mã nhân viên', max_length=100, primary_key=True)
    hoten = models.CharField('Họ và tên', max_length=100)
    gioitinh = models.CharField(max_length=3, choices=GENRE_CHOICES)
    dienthoai = models.IntegerField(default=0)
    diachi = models.CharField('Địa chỉ', max_length=255, null=True, blank=True)

    def __str__(self):
        return self.hoten


class ranh_gioi(models.Model):
    GENRE_CHOICES = (
        ('Phường', 'Phường'),
        ('Xã', 'Xã'),
    )
    ma_ranh_gioi = models.CharField('Mã ranh giới',max_length=100, primary_key=True)
    ten_ranh_gioi = models.CharField('Tên ranh giới', max_length=100)
    type_ranh_gioi= models.CharField('Loại ranh giới',max_length=6, choices=GENRE_CHOICES)
    geom = models.MultiPolygonField(srid=4326)
    ghichu = models.CharField(max_length=150, null=True, blank=True)
    def __str__(self):
        return self.ten_ranh_gioi
    def natural_key(self):
        return (self.ten_ranh_gioi)


class duonggiaothong(models.Model):
    ma_duong = models.CharField('Mã đường', max_length=100, primary_key=True)
    ten_duong = models.CharField('Tên đường', max_length=100)
    geom = models.MultiLineStringField(srid=4326)
    ghichu = models.CharField(max_length=150, null=True, blank=True)
    ranh_gioi_id = models.ForeignKey(ranh_gioi, verbose_name="Tên ranh giới", on_delete=models.CASCADE)

    def __str__(self):
        return self.ten_duong

    def natural_key(self):
        return (self.ten_duong)


class loaicay(models.Model):
    ma_loai_cay = models.CharField('mã loại cây', max_length=50, primary_key=True)
    ten_loai_cay = models.CharField('tên loại cây', max_length=100)

    def __str__(self):
        return self.ten_loai_cay

    def natural_key(self):
        return (self.ten_loai_cay)

class tinhtrangcay(models.Model):
    ten_tinh_trang= models.CharField('tên tình trạng cây', max_length=100)

    def __str__(self):
        return self.ten_tinh_trang

    def natural_key(self):
        return (self.ten_tinh_trang)


class cayxanh(models.Model):
    ma_cay = models.CharField(max_length=100, primary_key=True)
    ten_cay = models.CharField(max_length=100)
    chieucao = models.IntegerField()
    vitri = models.CharField(max_length=100)
    ngaytrong = models.DateField('Ngày trồng')
    tinhtrang_id = models.ForeignKey(tinhtrangcay, verbose_name="Tình trạng", on_delete=models.CASCADE)
    dacdiem = models.CharField('Đặc điểm ', max_length=200, null=True, blank=True)
    geom = models.PointField(srid=4326)
    duong_id = models.ForeignKey(duonggiaothong, verbose_name="Tên đường giao thông", on_delete=models.CASCADE)
    loaicay_id = models.ForeignKey(loaicay, verbose_name="Loại cây", on_delete=models.CASCADE)


    def __str__(self):
        return self.ma_cay

class chamsoccay(models.Model):
    cong_viec = models.CharField('Công việc', max_length=100)
    ngay_cham_soc = models.DateField('Ngày chăm sóc')
    nhanvien_id = models.ForeignKey(nhanvien, verbose_name="Nhân viên ", on_delete=models.CASCADE)
    cayxanh_id = models.ForeignKey(cayxanh, verbose_name="Cây xanh", on_delete=models.CASCADE)

    def __unicode__(self):
        return self.cayxanh_id

qlcayxanh/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm,SetPasswordForm
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from django.forms import ModelForm
from qlcayxanh import models
from qlcayxanh.models import *
from django.contrib.gis.db.models import MultiPolygonField
from django.contrib.gis import forms
from leaflet.forms.widgets import LeafletWidget
LEAFLET_WIDGET_ATTRS = {
    'map_height': '600px',
    'map_width': '50%',
    'display_raw': 'true',
    'map_srid': 4326,
}

class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True, label='Email')
    first_name = forms.CharField(max_length=30, required=False, help_text='Không bắt buộc.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Không bắt buộc')
    username = forms.CharField(required=True, help_text = _('Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.'))
    is_staff= forms.BooleanField(required=False)
    is_active = forms.BooleanField(required=False)
    is_superuser = forms.BooleanField(required=False)
    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'is_staff',
            'is_active',
            'is_superuser'
        )


class UserForm(UserChangeForm):
    class Meta:
        model = User
        fields = (
            'email',
            'first_name',
            'last_name',
            'is_staff',
            'is_active',
            'is_superuser'
        )

class Password_ChangeForm(SetPasswordForm):
    """
    A form that lets a user change their password by entering their old
    password.
    """
    error_messages = {
        **SetPasswordForm.error_messages,
        'password_incorrect': _("Mật khẩu cũ của bạn không đúng, vui lòng nhập lại."),
    }
    old_password = forms.CharField(
        label=_("Old password"),
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'current-password', 'autofocus': True}),
    )
    new_password1 = forms.CharField(  label=_("Nhập mật khẩu mới"),strip=False,widget=forms.PasswordInput(attrs={'autocomplete': 'current-password', 'autofocus': True}),help_text=(""))
    new_password2 = forms.CharField(label=_("Nhập lại mật khẩu mới"),strip=False,widget=forms.PasswordInput(attrs={'autocomplete': 'current-password', 'autofocus': True}),help_text=_(""))
    field_order = ['old_password', 'new_password1', 'new_password2']

    def clean_old_password(self):
        """
        Validate that the old_password field is correct.
        """
        old_password = self.cleaned_data["old_password"]
        if not self.user.check_password(old_password):
            raise ValidationError(
                self.error_messages['password_incorrect'],
                code='password_incorrect',
            )
        return old_password
# Nhân viên form
class nhanvienForm(ModelForm):
    class Meta:
        model = nhanvien
        fields = '__all__'
#---------------------------------------#
# ranh giới form
class ranhgioiForm(ModelForm):
    geom = forms.MultiPolygonField(
        widget=LeafletWidget(attrs=LEAFLET_WIDGET_ATTRS))
    class Meta:
        model = ranh_gioi
        fields = (
            'ma_ranh_gioi',
            'type_ranh_gioi',
            'ten_ranh_gioi',
            'geom',
            'ghichu'
        )
# cây xanh form
class cayxanhForm(ModelForm):
    geom = forms.PointField(
        widget=LeafletWidget(attrs=LEAFLET_WIDGET_ATTRS))
    class Meta:
        model = cayxanh
        fields = (
            'ma_cay',
            'ten_cay',
            'chieucao',
            'vitri',
            'ngaytrong',
            'tinhtrang_id',
            'dacdiem',
            'geom',
            'duong_id',
            'loaicay_id'
        )

# ----------------------------#
# Đường giao thông form
class streetsForm(ModelForm):
    geom = forms.MultiLineStringField(
        widget=LeafletWidget(attrs=LEAFLET_WIDGET_ATTRS))
    class Meta:
        model = duonggiaothong
        fields = (
            'ma_duong',
            'ten_duong',
            'geom',
            'ghichu',
            'ranh_gioi_id'
        )
# Chăm sóc cây
class chamsoccayForm(ModelForm):
    class Meta:
        model = chamsoccay
        fields = (
            'cong_viec',
            'ngay_cham_soc',
            'nhanvien_id',
            'cayxanh_id'
        )
class treeSearchForm(forms.ModelForm):
    class Meta:
        model = cayxanh
        fields = ['ma_cay','ten_cay','loaicay_id']

class loaicayForm(ModelForm):
    class Meta:
        model = loaicay
        fields = '__all__'

class tinhtrangcayForm(ModelForm):
    class Meta:
        model = tinhtrangcay
        fields = '__all__'

qlcayxanh/templates/home/qltcotrees/edit.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    {% load leaflet_tags %}
    <head>
        {% leaflet_js %}
        {% leaflet_css %}
     {% include 'include/includecss.html' %}

    <link rel="stylesheet"  href="{% static 'home/tcotrees/css/bootstrap.css' %}"  />
    <!-- Custom Styles-->
    <link rel="stylesheet"  href="{% static 'home/css/menu.css' %}"  />
    <link rel="stylesheet"  href="{% static 'home/tcotrees/css/addtcotree.css' %}"  />
    <link type="text/css" rel="stylesheet" href="{% static 'home/tcotrees/css/web.assets_common.0.css' %}"/>
    <link type="text/css" rel="stylesheet" href="{% static 'home/tcotrees/css/web.assets_backend.0.css' %}"/>
    <link type="text/css" rel="stylesheet" href="{% static 'home/tcotrees/css/web.assets_backend.1.css' %}"/>
    <!-- show map -->
    <script src="{% static 'home/tcotrees/css/jsi18n/' %}">  </script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/ol3/4.6.5/ol.css" type="text/css" media="all" rel="stylesheet">
    <link  href="{% static 'home/tcotrees/css/ol3.css' %}"  type="text/css" media="all" rel="stylesheet" />
    <script src="{% static 'home/tcotrees/js/jquery.js' %}">  </script>
    <script src="{% static 'home/tcotrees/js/ol.js' %}">  </script>
    <script src="{% static 'home/tcotrees/js/jquery.init.js' %}">  </script>
    <script src="{% static 'home/tcotrees/js/OLMapWidget.js' %}">  </script>
    <script src="{% static 'home/tcotrees/js/core.js' %}">  </script>
    <script src="{% static 'home/tcotrees/js/RelatedObjectLookups.js' %}">  </script>
    <script src="{% static 'home/tcotrees/js/actions.js/' %}">  </script>
    <script src="{% static 'home/tcotrees/js/urlify.js' %}">  </script>
    <script src="{% static 'home/tcotrees/js/prepopulate.js' %}">  </script>
    <script src="{% static 'home/tcotrees/js/xregexp.js' %}">  </script>
    </head>
    <body>
        <div id="wrapper">
            {% include 'include/base.html' %}
            <div id="page-wrapper">
                <div class="header">
                    <div class="row user-infos cyruxx">
                        <div class="col-xs-12 col-sm-12 col-md-10 col-lg-10 col-xs-offset-0 col-sm-offset-0 col-md-offset-1 col-lg-offset-1"></div>
                        <div class="panel panel-primary">
                            <div class="panel-heading">
                                <h1 class="panel-title">Sửa thông tin chăm sóc cây</h1>
                            </div>
                            <div class="panel-body">
                                {% if form.errors %}
                                {% for field in form %}
                                {% for error in field.errors %}
                                <div class="alert alert-danger">
                                    <strong>{{ error|escape }}</strong>
                                </div>
                                {% endfor %}
                                {% endfor %}
{% endif %}
                                <!-- DỰ ÁN MỚI -->
                                <div class="o_content">
                                    <div class="o_view_controller">
                                        <div class="o_form_view o_form_editable">
                                            <div class="o_form_sheet_bg">
                                                <div class="clearfix o_form_sheet">
                                                    <div class="o_group">
                                                        <form class="form-inline my-2 my-lg-0"   method="POST">
                                                            {% csrf_token %}
                                                            <table class="o_group o_inner_group o_group_col_6">
                                                                <tbody>
                                                                    <tr>
                                                                        <td class="o_td_label"><label class="o_form_label o_required_modifier"  for="id_cong_viec">Công việc:</label></td>
                                                                        <td style="width: 100%;"><input class="o_field_char o_field_widget o_input o_required_modifier" type="text" name="cong_viec"  value="{{ tcotree.cong_viec }}"required id="id_cong_viec" ></td>
                                                                    </tr>
                                                                    <tr> {{ form.ngaytrong.errors }}
                                                                        <td class="o_td_label"><label class="o_form_label o_required_modifier" for="id_ngay_cham_soc">Ngày chăm sóc:</label></td>
                                                                        <td style="width: 100%;"><input class="o_field_char o_field_widget o_input o_required_modifier" type="date" name="ngay_cham_soc" id="id_ngay_cham_soc" value='{{ tcotree.ngay_cham_soc|date:"Y-m-d" }}'></td>
                                                                    </tr>
                                                                </tbody>
                                                            </table><table class="o_group o_inner_group o_group_col_6"><tbody>
                                                                <tr>
                                                                    <td class="o_td_label"><label class="o_form_label o_required_modifier" for="id_nhanvien_id">Nhân viên:</label></td>
                                                                    <td style="width: 100%;">
                                                                       {{ form.nhanvien_id }}
                                                                         <!-- Sửa -->
                                                                        <a class="related-widget-wrapper-link add-related"
                                                                         href="{% url 'qlcayxanh:update_staffs' tcotree.nhanvien_id_id %}" onclick="return popitup('/index/update_staffs/{{tcotree.nhanvien_id_id}}/')"
                                                                         title="Sửa nhân viên khác"><img src="/static/admin/img/icon-changelink.svg" alt="Edit"></a>
                                                                       <!-- Thêm nhân viên -->
                                                                       <a class="related-widget-wrapper-link add-related"
                                                                       href="{% url 'qlcayxanh:addstaffs' %}"onclick="return popitup('/index/add_staff')"
                                                                       title="Thêm nhân viên khác"><img src="/static/admin/img/icon-addlink.svg" alt="Add"></a>
                                                                    </td>
                                                                    </tr>
                                                                    <tr>
                                                                        <td class="o_td_label"><label class="o_form_label o_required_modifier" for="id_cayxanh_id">Cây xanh:</label></td>
                                                                        <td style="width: 100%;">
                                                                           {{ form.cayxanh_id }}
                                                                             <!-- Sửa -->
                                                                             <a class="related-widget-wrapper-link add-related"
                                                                             href="{% url 'qlcayxanh:update_trees' tcotree.cayxanh_id_id %}" onclick="return popitup1('/index/update_trees/{{tcotree.cayxanh_id_id}}/')"
                                                                             title="Sửa đường giao thông khác"><img src="/static/admin/img/icon-changelink.svg" alt="Edit"></a>
                                                                           <!-- Thêm cây -->
                                                                           <a class="related-widget-wrapper-link add-related"
                                                                           href="{% url 'qlcayxanh:addcayxanh' %}"onclick="return popitup1('/index/add_tree')"
                                                                           title="Thêm cây xanh khác"><img src="/static/admin/img/icon-addlink.svg" alt="Add"></a>
                                                                        </td>
                                                                        </tr>
                                                                </tbody>
</table>
                                                    <div class="post_center" style="margin-top:66px;">
                                                        <button class="submit-btn" type="submit" >Cập nhật</button>
                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                                        <a class="quayve" href="{% url 'qlcayxanh:lists_tcotrees' %}">Quay về danh sách</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!--                    -->
            </div>
        </div>
    </div>
</div>
</div>
</div>
    <script language="javascript" type="text/javascript">
    function popitup(url) {
        newwindow=window.open(url,'{{title}}','height=626,width=1000');
        if (window.focus) {newwindow.focus()}
        return false;
    }
    </script>
    <script language="javascript" type="text/javascript">
        function popitup1(url) {
            newwindow=window.open(url,'{{title}}','height=600,width=1200');
            if (window.focus) {newwindow.focus()}
            return false;
        }
    </script>
        {% include 'include/filescript.html' %}
    <script src="{% static 'home/tcotrees/js/validuser.js' %}"></script>
    </body>
</html>

qlcayxanh/templates/home/qltcotrees/infstaff.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
    {% load leaflet_tags %}
    <head>
        {% leaflet_js %}
        {% leaflet_css %}
        {% include 'include/includecss.html' %}

    <link rel="stylesheet"  href="{% static 'home/tcotrees/css/bootstrap.css' %}"  />
    <!-- Custom Styles-->
    <link rel="stylesheet"  href="{% static 'home/css/menu.css' %}"  />
    <link rel="stylesheet"  href="{% static 'home/tcotrees/css/addboun.css' %}"  />
    <link type="text/css" rel="stylesheet" href="{% static 'home/tcotrees/css/web.assets_common.0.css' %}"/>
    <link type="text/css" rel="stylesheet" href="{% static 'home/tcotrees/css/web.assets_backend.0.css' %}"/>
    <link type="text/css" rel="stylesheet" href="{% static 'home/tcotrees/css/web.assets_backend.1.css' %}"/>
<!-- show map -->
    <script src="{% static 'home/tcotrees/css/jsi18n/' %}">  </script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/ol3/4.6.5/ol.css" type="text/css" media="all" rel="stylesheet">
    <link  href="{% static 'home/tcotrees/css/ol3.css' %}"  type="text/css" media="all" rel="stylesheet" />
    <script src="{% static 'home/tcotrees/js/jquery.js' %}">  </script>
    <script src="{% static 'home/tcotrees/js/ol.js' %}">  </script>
    <script src="{% static 'home/tcotrees/js/jquery.init.js' %}">  </script>
    <script src="{% static 'home/tcotrees/js/OLMapWidget.js' %}">  </script>
    <script src="{% static 'home/tcotrees/js/core.js' %}">  </script>
    <script src="{% static 'home/tcotrees/js/RelatedObjectLookups.js' %}">  </script>
    <script src="{% static 'home/tcotrees/js/actions.js/' %}">  </script>
    <script src="{% static 'home/tcotrees/js/urlify.js' %}">  </script>
    <script src="{% static 'home/tcotrees/js/prepopulate.js' %}">  </script>
    <script src="{% static 'home/tcotrees/js/xregexp.js' %}">  </script>
</head>

<body>
   <div id="wrapper">
            {% include 'include/base.html' %}
            <div id="page-wrapper">
                <div class="header">
                    <div class="row user-infos cyruxx">
                        <div class="col-xs-12 col-sm-12 col-md-10 col-lg-10 col-xs-offset-0 col-sm-offset-0 col-md-offset-1 col-lg-offset-1"></div>
                        <div class="panel panel-primary">
                            <div class="panel-heading">
                                <h1 class="panel-title">Thông tin nhân viên {{ staff.ma_nhan_vien}}</h1>
                            </div>
                            <div class="panel-body">
                                <!-- DỰ ÁN MỚI -->
                                <div class="o_content">
                                    <div class="o_view_controller">
                                        <div class="o_form_view o_form_editable">
                                            <div class="o_form_sheet_bg">
                                                <div class="clearfix o_form_sheet">
                                                    <div class="o_group">

                                                            <table class="o_group o_inner_group o_group_col_6">
                                                                <tbody>
                                                                    <tr>
                                                                        <td class="o_td_label"><label  for="id_ma_nhan_vien">Mã nhân viên:</label></td>
                                                                        <td style="width: 100%;"><input style="color:red;"  type="text" name="ma_nhan_vien" value="{{ staff.ma_nhan_vien }}"readonly="true" id="id_ma_nhan_vien" ></td>
                                                                    </tr>
                                                                    <tr>
                                                                        <td class="o_td_label"><label  for="id_hoten">Tên nhân viên:</label></td>
                                                                        <td style="width: 100%;"><input  readonly="true" type="text" name="hoten" value="{{ staff.hoten }}"maxlength="100" required id="id_hoten"></td>
                                                                    </tr>

                                                                    <tr>
                                                                        <td class="o_td_label"><label  for="id_vitri">Điện thoại:</label></td>
                                                                        <td style="width: 100%;">{{ staff.dienthoai }}
                                                                    </tr>
                                                                </tbody>
                                                            </table><table class="o_group o_inner_group o_group_col_6"><tbody><tr>
                                                                        <td class="o_td_label"><label  for="id_gioitinh">Giới tính:</label></td>
                                                                        <td style="width: 100%;"><input  type="text" value="{{ staff.gioitinh }}" readonly="true"name="gioitinh" id="id_gioitinh" ></td>
                                                                    </tr>
                                                                    <tr>
                                                                        <td class="o_td_label"><label >Địa chỉ:</label></td>
                                                                        <td style="width: 100%;">
                                                                            {{ staff.diachi}}
                                                                        </td>
                                                                    </tr>

                                                                </tbody>
                                                            </table>
                                                    </div>
                                                </div>
                                                <a class="quayve" href="{% url 'qlcayxanh:lists_tcotrees' %}">Quay về danh sách</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!--                    -->
                    </div>
                </div>
            </div>
        </div>
        </div>
        </div>
   {% include 'include/filescript.html' %}
    <script src="{% static 'home/tcotrees/js/validuser.js' %}"></script>
</body>

</html>